language: objective-c
osx_image: xcode9.2

before_install:
  - rvm use $RVM_RUBY_VERSION
  # - bundle install
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods -v '1.3.1' --no-document --quiet;
  - gem install slather --no-document --quiet;  
  - pod install --repo-update;
  # - carthage bootstrap --verbose --platform iOS --cache-builds --use-ssh 

script:
  - set -o pipefail && bundle exec fastlane travis

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'FlexLayout' -J 'FlexLayoutTests'
